# Generated by Django 3.0.6 on 2020-06-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='altura',
            field=models.FloatField(verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estadoCivil',
            field=models.CharField(max_length=10, verbose_name='estadoCivil'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.FloatField(verbose_name='Peso'),
        ),
    ]
